# Generated by Django 5.0.4 on 2024-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_body_blogcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='order',
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='element_type',
            field=models.CharField(choices=[('heading', 'Заголовок'), ('paragraph', 'Абзац'), ('list', 'Список'), ('image', 'Картина')], max_length=10),
        ),
    ]
